### ISSUE TITLE
some extra parameters

### ISSUE THREAD

**Issue by tissatussa** [cosmobobak/uci-suite#1]
hi! i really like your simple script, it simply does exactly what i expect ! Nice colored output, works with many (all?) of my UCI engines (i'm on Linux).

but i'm not into Rust .. i managed to change some parameters in the .rs file to create custom time-per-move and epd file, then compile again .. Could you add parameters for those 2 values, like the engine path ? That would make your tool real handy.

![uci-suite-custom](https://github.com/cosmobobak/uci-suite/assets/1109281/61a802b6-95b8-4d4c-9885-85c9b3948ae6)

**Comment by tissatussa** [comment]
oops !
i just discovered your --help option, which gives me my answer :

```
$ ./uci-suite_wac_10sec --help
Usage: uci-suite_wac_10sec [OPTIONS] <ENGINE>

Arguments:
  <ENGINE>  Path to a UCI chess engine to run on the test suite

Options:
      --inbuilt <NAME>       Selection of inbuilt EPD test suites to run. Valid values are `winatchess`, `zugzwangs`, and `tablebases`
      --epdpath <PATH>       Path to an Extended Position Description file to use
      --option <NAME=VALUE>  UCI options to set before running the test suite
  -v, --verbose              Run the test suite in verbose mode
      --debug                Run the test suite in debug mode
      --time <MILLISECONDS>  Time the engine should spend on each position, in milliseconds
  -h, --help                 Print help
  -V, --version              Print version

```

that's what i wanted !

**Comment by cosmobobak** [comment]
glad you figured it out!

**Comment by tissatussa** [comment]
And i'm glad you responded this way, because i have a question.
The help info states :

```
--inbuilt <NAME>
Selection of inbuilt EPD test suites to run. Valid values are winatchess, zugzwangs, and tablebases
```

when i look into the code of `main.rs` i see the variable `WIN_AT_CHESS` is used at the start of `main()` this way :

```
// Read the EPD file into a string.
let epd_text = cli.epdpath.as_deref().map_or(WIN_AT_CHESS, |path| {
    std::fs::read_to_string(path)
        .expect("Failed to read EPD file")
        .leak()
});
```

it seems this makes `wac.epd` default .. i also conclude the contents of this file is embedded in the binary, because i can successfully run it without having a folder called 'epds' .. but when using the `--inbuilt` argument with value `zugzwangs` or `tablebases`, i get an error .. as if these concerning .epd files are NOT embedded .. however, supplying argument `--epdpath` and an existing .epd file DOES work .. is your code wrong here ? How can i properly use the `--inbuilt` argument ? I'd like to have 1 default .epd file (the wac one) when giving no `--epdpath` .. i tried to change the code but i didn't succeed because i'm not into Rust ..

btw. does the info string _"Valid values are winatchess, zugzwangs, and tablebases"_ come from the shakmaty module ? I guess so, i don't see this text in main.rs ..

**Comment by cosmobobak** [comment]
this program is very much under-construction, so bugs like this are to be expected - i'd generally avoid using the `inbuilt` option for now, i'm not sure that i've done it quite correctly. the info string comes from the comments in the CLI module.

**Comment by tissatussa** [comment]
these days i'm still using this program to test engines with several "Test Suite" EPD files and it works properly, i encounter no errors. Indeed i avoid using the `--inbuilt` option, i just use the `--epdpath` option to set a custom EPD file.

i also discovered how an UCI option like "Use MCTS" (*), which name contains a space (!), can be used as argument on the command line : put single quotes around it, like `--option 'Use MCTS'=true` ! You could add this to the README ?
*) eg. the Komodo engine has this UCI option.

besides that, i made a little hack .. although i'm not into Rust, but it was simple : when using the `--verbose` option (which is a nice feature) often a lot of info lines are displayed which are irrelevant, eg.:

```
info currmove g3h4 currmovenumber 2
info nodes 14874274
```

to me only lines containing 'score' should be displayed.
so, i changed your code like this :

```
// wait for the engine to respond with `bestmove <move>`
let mut engine_response;
loop {
    engine_response = read_line(cli.debug, &mut engine_stdout)?;

    if engine_response.contains(" score ") {
        if cli.verbose {
            println!(
                "[{CONTROL_GREY}{id:midl$}{CONTROL_RESET}] {}",
                engine_response.trim(),
                midl = maxidlen,
                id = epd.id,
            );
        }
    }

    if engine_response.contains("bestmove") {
        if cli.verbose {
            println!(
                "[{CONTROL_GREY}{id:midl$}{CONTROL_RESET}] {}",
                engine_response.trim(),
                midl = maxidlen,
                id = epd.id,
            );
        }
        break;
    }
}
```

and it works !

thanks for this great little program.

**Comment by cosmobobak** [comment]
You should be able to enclose the whole option with quotes, like "Use MCTS=true".
I'll take a look at your recommendation later today.

**Comment by tissatussa** [comment]
i stated your script has few faults and runs fine, it even checks if all EPD lines have the correct syntax, eg.:

`4K2R/2k4p/8/8/3pp3/R2p4/3P4/7r w - - bm Ra4, Ra7+; id "W.Eigenmann: Brillant 090";`

```
$ ./uci-suite --epdpath ./100Brillante.epd --time 30000 ./Rice-v7.0.0 
Error: invalid san: Ra4,
Caused by: invalid san
```

it seems no comma's (',') are allowed to seperate multi bm's, they must be spaces : after removing the comma after 'Ra4' this line is accepted. You could add a parameter like "Skip invalid EPD lines True/False" ?

these EPD files also might contain 'am' : Avoid Move(s) .. i forgot the proper syntax when also bm(s) are defined - i'm sure you can find info about that .. am's are nice : these moves should NOT be played, it gives -1 point in some other applications i know. You could easily deal with such 'am' data - you decide ?

you could add a prefix counter like 3/100 to indicate which EPD line is currently processed from /total.

hope you find time to create v1.0.2 :-)

**Comment by tissatussa** [comment]
another thing which may be interesting and probably easy to implement : at each EPD output line, besides the time spent by the engine you could display the depth reached. This extra info refers to the speed of the engine, unlike nodes/sec.
